-- INSERT INTO tb_veterinario(cpf, email, nome) VALUES ('000.000.000-00', 'emailZe@gmail.com', 'Ze da Silva');

INSERT INTO tb_pessoa(cpf, nome, email, senha, foto) VALUES ('12345678911', 'Ricardo Lucas da Silva', 'ricardo@gmail.com.br', '123', 'https://img.freepik.com/fotos-premium/feche-o-rosto-retrato-medico-homem-idoso-medico-especialista-clinico-geral-trabalho-em_717737-2660.jpg');
INSERT INTO tb_pessoa(cpf, nome, email, senha) VALUES ('78945612332', 'Alberto Campos', 'alberto@gmail.com.br', '456');
INSERT INTO tb_pessoa(cpf, nome, email, senha) VALUES ('15948723159', 'Lucas dos Santos', 'lucas@yahoo.com.br', '789');

INSERT INTO tb_veterinario(id, crmv) VALUES(1, '65465462');

INSERT INTO pessoa_telefones(pessoa_id, telefones) VALUES (1, '9-0000-0000');
INSERT INTO pessoa_telefones(pessoa_id, telefones) VALUES (1, '9-1111-1111');
INSERT INTO pessoa_telefones(pessoa_id, telefones) VALUES (2, '9-2222-2222');

INSERT INTO tb_especialidade(especialidade) VALUES('Dermatologia');
INSERT INTO tb_especialidade(especialidade) VALUES('Acupuntura');
INSERT INTO tb_especialidade(especialidade) VALUES('Cardiologista');

INSERT INTO tb_vet_esp(vet_id, esp_id) VALUES(1, 1);

INSERT INTO tb_tipo_animal(nome) VALUES ('Cachorro');
INSERT INTO tb_tipo_animal(nome) VALUES ('Gato');
INSERT INTO tb_tipo_animal(nome) VALUES ('Passaro');
INSERT INTO tb_tipo_animal(nome) VALUES ('Peixe');

INSERT INTO tb_estados(nome) VALUES('Acre');
INSERT INTO tb_estados(nome) VALUES('Alagoas');
INSERT INTO tb_estados(nome) VALUES('Amapa');
INSERT INTO tb_estados(nome) VALUES('Amazonas');
INSERT INTO tb_estados(nome) VALUES('Bahia');
INSERT INTO tb_estados(nome) VALUES('Ceara');
INSERT INTO tb_estados(nome) VALUES('Distrito Federal');
INSERT INTO tb_estados(nome) VALUES('Espirito Santo');
INSERT INTO tb_estados(nome) VALUES('Goias');
INSERT INTO tb_estados(nome) VALUES('Maranhao');
INSERT INTO tb_estados(nome) VALUES('Mato Grosso');
INSERT INTO tb_estados(nome) VALUES('Mato Grosso do Sul');
INSERT INTO tb_estados(nome) VALUES('Minas Gerais');
INSERT INTO tb_estados(nome) VALUES('Para');
INSERT INTO tb_estados(nome) VALUES('Paraiba');
INSERT INTO tb_estados(nome) VALUES('Parana');
INSERT INTO tb_estados(nome) VALUES('Pernambuco');
INSERT INTO tb_estados(nome) VALUES('Piaui');
INSERT INTO tb_estados(nome) VALUES('Rio de Janeiro');
INSERT INTO tb_estados(nome) VALUES('Rio Grande do Norte');
INSERT INTO tb_estados(nome) VALUES('Rio Grande do Sul');
INSERT INTO tb_estados(nome) VALUES('Rondonia');
INSERT INTO tb_estados(nome) VALUES('Roraima');
INSERT INTO tb_estados(nome) VALUES('Santa Catarina');
INSERT INTO tb_estados(nome) VALUES('Sao Paulo');
INSERT INTO tb_estados(nome) VALUES('Sergipe');
INSERT INTO tb_estados(nome) VALUES('Tocantins');

-- Inserção de uma cidade fictícia para cada estado
INSERT INTO tb_cidades(nome, estado_id) VALUES('Acrelândia', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Assis Brasil', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Brasiléia', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bujari', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Capixaba', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cruzeiro do Sul', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Epitaciolândia', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Feijó', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jordão', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mâncio Lima', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Manoel Urbano', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Marechal Thaumaturgo', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Plácido de Castro', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Acre', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Walter', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rio Branco', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rodrigues Alves', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Rosa do Purus', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sena Madureira', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Senador Guiomard', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tarauacá', 1);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Xapuri', 1);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Água Branca', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Anadia', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Arapiraca', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Atalaia', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barra de Santo Antônio', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barra de São Miguel', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Batalha', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Belém', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Belo Monte', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Boca da Mata', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Branquinha', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cacimbinhas', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cajueiro', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campestre', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campo Alegre', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campo Grande', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canapi', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Capela', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Carneiros', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Chã Preta', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Coité do Nóia', 2);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Colônia Leopoldina', 2);




INSERT INTO tb_cidades(nome, estado_id) VALUES('Amapá', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Calçoene', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cutias', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ferreira Gomes', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itaubal', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Laranjal do Jari', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Macapá', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mazagão', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Oiapoque', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pedra Branca do Amapari', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Grande', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pracuúba', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santana', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Serra do Navio', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tartarugalzinho', 3);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Vitória do Jari', 3);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Alvarães', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Amaturá', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Anamã', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Anori', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Apuí', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Atalaia do Norte', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Autazes', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barcelos', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barreirinha', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Benjamin Constant', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Beruri', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Boa Vista do Ramos', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Boca do Acre', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Borba', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caapiranga', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canutama', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Carauari', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Careiro', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Careiro da Várzea', 4);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Coari', 4);



INSERT INTO tb_cidades(nome, estado_id) VALUES('Salvador', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Feira de Santana', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Vitória da Conquista', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Camaçari', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itabuna', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Juazeiro', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ilhéus', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Lauro de Freitas', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jequié', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Teixeira de Freitas', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barreiras', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alagoinhas', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Seguro', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Simões Filho', 5);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Paulo Afonso', 5);


INSERT INTO tb_cidades(nome, estado_id) VALUES('Fortaleza', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caucaia', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Juazeiro do Norte', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Maracanaú', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sobral', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Crato', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itapipoca', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Maranguape', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Iguatu', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Quixadá', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pacajus', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Crateús', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Russas', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Aquiraz', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canindé', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pacatuba', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Quixeramobim', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Aracati', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tianguá', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Acaraú', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Morada Nova', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Icó', 6);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Quixé', 6);


INSERT INTO tb_cidades(nome, estado_id) VALUES('Brasília', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Gama', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Taguatinga', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Brazlândia', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sobradinho', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Planaltina', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Paranoá', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Núcleo Bandeirante', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ceilândia', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guará', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cruzeiro', 7);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Samambaia', 7);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Vitória', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Vila Velha', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cariacica', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Serra', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Linhares', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cachoeiro de Itapemirim', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guarapari', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Colatina', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itapemirim', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Aracruz', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Venécia', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barra de São Francisco', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Castelo', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Mateus', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Maria de Jetibá', 8);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Viana', 8);


INSERT INTO tb_cidades(nome, estado_id) VALUES('Goiânia', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Aparecida de Goiânia', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Anápolis', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Luziânia', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Valparaíso de Goiás', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Trindade', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Formosa', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Novo Gama', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Águas Lindas de Goiás', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Senador Canedo', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caldas Novas', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rio Verde', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itumbiara', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Catalão', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jaraguá', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Uruaçu', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Porangatu', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jataí', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Inhumas', 9);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bela Vista de Goiás', 9);

INSERT INTO tb_cidades(nome, estado_id) VALUES('São Luís', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Imperatriz', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São José de Ribamar', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Timon', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caxias', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Codó', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Paço do Lumiar', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Açailândia', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bacabal', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Balsas', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Inês', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barra do Corda', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pinheiro', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Chapadinha', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Coroatá', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itapecuru-Mirim', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São José de Ribamar', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Viana', 10);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pedreiras', 10);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Cuiabá', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Várzea Grande', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rondonópolis', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sinop', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tangará da Serra', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cáceres', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sorriso', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Lucas do Rio Verde', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Primavera do Leste', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barra do Garças', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alta Floresta', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pontes e Lacerda', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Mutum', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campo Verde', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Juína', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sapezal', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Colniza', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Comodoro', 11);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Diamantino', 11);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Campo Grande', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Dourados', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Três Lagoas', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Corumbá', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ponta Porã', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sidrolândia', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Naviraí', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Andradina', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Aquidauana', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Maracaju', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Amambai', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rio Brilhante', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Coxim', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jardim', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bonito', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Alvorada do Sul', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cassilândia', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ivinhema', 12);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bataguassu', 12);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Belo Horizonte', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Uberlândia', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Contagem', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Juiz de Fora', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Betriz', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Montes Claros', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ribeirão das Neves', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Uberaba', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Governador Valadares', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ipatinga', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sete Lagoas', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Divinópolis', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Luzia', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ibirité', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Teófilo Otoni', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sabará', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Poços de Caldas', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Patos de Minas', 13);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Varginha', 13);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Belém', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ananindeua', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santarém', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Marabá', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Castanhal', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Parauapebas', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itaituba', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bragança', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Abaetetuba', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cametá', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araguaína', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Marituba', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Benevides', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Igarapé-Miri', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Moju', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tucuruí', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Oriximiná', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Altamira', 14);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barcarena', 14);

INSERT INTO tb_cidades(nome, estado_id) VALUES('João Pessoa', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campina Grande', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Rita', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Patos', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bayeux', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sousa', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cajazeiras', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cabedelo', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guarabira', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Luzia', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mamanguape', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Queimadas', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Esperança', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pombal', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itabaiana', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pedras de Fogo', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Lagoa Seca', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mari', 15);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Conde', 15);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Curitiba', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Londrina', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Maringá', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ponta Grossa', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cascavel', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São José dos Pinhais', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Foz do Iguaçu', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Colombo', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guarapuava', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Paranaguá', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Toledo', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Apucarana', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pinhais', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araucária', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campo Largo', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Umuarama', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Piraquara', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cambé', 16);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pato Branco', 16);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Recife', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jaboatão dos Guararapes', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Olinda', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caruaru', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Petrolina', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Paulista', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cabo de Santo Agostinho', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Camaragibe', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Garanhuns', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Vitória de Santo Antão', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Igarassu', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Lourenço da Mata', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Abreu e Lima', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Cruz do Capibaribe', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araripina', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Serra Talhada', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ipojuca', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pesqueira', 17);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Surubim', 17);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Teresina', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Parnaíba', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Picos', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campo Maior', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Floriano', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Piripiri', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Altos', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barras', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Esperantina', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Valença do Piauí', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Raimundo Nonato', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('União', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Oeiras', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bom Jesus', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Luís Correia', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canto do Buriti', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Batalha', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Piracuruca', 18);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Corrente', 18);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Rio de Janeiro', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Gonçalo', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Duque de Caxias', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Iguaçu', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Niterói', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Belford Roxo', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campos dos Goytacazes', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São João de Meriti', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Petrópolis', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Volta Redonda', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Magé', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itaboraí', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mesquita', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nilópolis', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Maricá', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cabo Frio', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Friburgo', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Queimados', 19);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Barra Mansa', 19);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Natal', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mossoró', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Parnamirim', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Gonçalo do Amarante', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ceará-Mirim', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Macaíba', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caicó', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Currais Novos', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Assu', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pau dos Ferros', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Cruz', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Areia Branca', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('João Câmara', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Macau', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canguaretama', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Apodi', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Touros', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Baraúna', 20);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Goianinha', 20);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Alegre', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caxias do Sul', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canoas', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pelotas', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Maria', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Gravataí', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Viamão', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Novo Hamburgo', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Leopoldo', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alvorada', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Passo Fundo', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Uruguaiana', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santa Cruz do Sul', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cachoeirinha', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bagé', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bento Gonçalves', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Esteio', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rio Grande', 21);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Erechim', 21);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Velho', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ji-Paraná', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ariquemes', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Vilhena', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cacoal', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guajará-Mirim', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jaru', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rolim de Moura', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pimenta Bueno', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ouro Preto do Oeste', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Mamoré', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Candeias do Jamari', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alvorada D Oeste', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alta Floresta D Oeste', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Espigão D Oeste', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Buritis', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Machadinho D Oeste', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Parecis', 22);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Presidente Médici', 22);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Boa Vista', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caracaraí', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rorainópolis', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São João da Baliza', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mucajaí', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pacaraima', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Cantá', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Amajari', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alto Alegre', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bonfim', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Normandia', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Iracema', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Uiramutã', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Pacaraima', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Luiz', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caroebe', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Iracema', 23);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mucajaí', 23);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Florianópolis', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Joinville', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Blumenau', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São José', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Criciúma', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Chapecó', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itajaí', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jaraguá do Sul', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Lages', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Palhoça', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Balneário Camboriú', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Brusque', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Bento do Sul', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Caçador', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Concórdia', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tubarão', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araranguá', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Rio do Sul', 24);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Joaçaba', 24);

INSERT INTO tb_cidades(nome, estado_id) VALUES('São Paulo', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guarulhos', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Campinas', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Bernardo do Campo', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santo André', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Osasco', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São José dos Campos', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Ribeirão Preto', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Sorocaba', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Mauá', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Santos', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Diadema', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Jundiaí', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Piracicaba', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Carapicuíba', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Bauru', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itaquaquecetuba', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Vicente', 25);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guarujá', 25);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Aracaju', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nossa Senhora do Socorro', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Lagarto', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itabaiana', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('São Cristóvão', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Estância', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nossa Senhora da Glória', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Propriá', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Itabaianinha', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Capela', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Simão Dias', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Umbaúba', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Boquim', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Canindé de São Francisco', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Poço Redondo', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nossa Senhora das Dores', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tobias Barreto', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Laranjeiras', 26);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Riachão do Dantas', 26);

INSERT INTO tb_cidades(nome, estado_id) VALUES('Palmas', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araguaína', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Gurupi', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Porto Nacional', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Paraíso do Tocantins', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Formoso do Araguaia', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Colinas do Tocantins', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Guaraí', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araguatins', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Dianópolis', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Tocantinópolis', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Miracema do Tocantins', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Nova Olinda', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Alvorada', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Xambioá', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Taguatinga', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Araguaçu', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Wanderlândia', 27);
INSERT INTO tb_cidades(nome, estado_id) VALUES('Palmeirante', 27);